#-----------------------------------------------------------------------
# TITLE:
#    pkgModules.tcl
#
# PROJECT:
#    athena - Athena Regional Stability Simulation
#
# DESCRIPTION:
#    ahttpd(n) package modules file
#
#    Generated by Kite.
#-----------------------------------------------------------------------

#-----------------------------------------------------------------------
# Package Definition

# -kite-provide-start  DO NOT EDIT THIS BLOCK BY HAND
package provide ahttpd 6.3.0a7
# -kite-provide-end

#-----------------------------------------------------------------------
# Required Packages

# Add 'package require' statements for this package's external 
# dependencies to the following block.  Kite will update the versions 
# numbers automatically as they change in project.kite.

# -kite-require-start ADD EXTERNAL DEPENDENCIES
package require md5 2.0.7
package require counter 2.0
# -kite-require-end

#-----------------------------------------------------------------------
# Namespace definition

namespace eval ::ahttpd:: {
    variable library [file dirname [info script]]
}


#-----------------------------------------------------------------------
# Modules

package require httpd 1.7

# httpd sub-packages
package require httpd::utils    ;# For Stderr

package require httpd::url      ;# URL dispatching
package require httpd::mtype    ;# Mime types
package require httpd::redirect ;# URL redirection
package require httpd::auth     ;# Basic authentication
package require httpd::digest   ;# Digest authentication
package require httpd::doc
package require httpd::dirlist  ;# Directory listings
package require httpd::include  ;# Server side includes
package require httpd::direct   ;# Application Direct URLs
package require httpd::status   ;# Built in status counters
package require httpd::debug    ;# Debug utilites

source [file join $::ahttpd::library server.tcl ]
source [file join $::ahttpd::library log.tcl    ]
source [file join $::ahttpd::library stats.tcl  ]
