#-------------------------------------------------------------------------
# TITLE:
#    pkgIndex.tcl
#
# PROJECT:
#    athena - Athena Regional Stability Simulation
#
# DESCRIPTION:
#    app_athena(n) package index file
#
#    Generated by Kite.
#-------------------------------------------------------------------------

# -kite-ifneeded-start  DO NOT EDIT THIS BLOCK BY HAND
package ifneeded app_athena 6.4.0a1 [list source [file join $dir pkgModules.tcl]]
# -kite-ifneeded-end
