#-----------------------------------------------------------------------
# TITLE:
#    pkgModules.tcl
#
# PROJECT:
#    athena - Athena Regional Stability Simulation
#
# DESCRIPTION:
#    app_athena(n) package modules file
#
#    Generated by Kite.
#-----------------------------------------------------------------------

#-----------------------------------------------------------------------
# Package Definition

# -kite-provide-start  DO NOT EDIT THIS BLOCK BY HAND
package provide app_athena 6.3.0a5
# -kite-provide-end

#-----------------------------------------------------------------------
# Is Tk loaded?
#
# For athena(1), Tk is already loaded, and we have a GUI.
# For athena_batch(1), Tk is not loaded, and we will not have a GUI.

set ::tkLoaded [expr {[info command tk] ne ""}]

#-----------------------------------------------------------------------
# Required Packages

# Add 'package require' statements for this package's external 
# dependencies to the following block.  Kite will update the versions 
# numbers automatically as they change in project.kite.

# -kite-require-start ADD EXTERNAL DEPENDENCIES
package require projectlib
package require -exact athena 6.3.0a5

namespace import ::projectlib::*
namespace import ::athena::*

# For Tk applications
if {$::tkLoaded} {
    package require ctext 3.3
    package require projectgui
    namespace import projectgui::*

}

# -kite-require-end

#-----------------------------------------------------------------------
# Namespace definition

namespace eval ::app_athena:: {
    variable library [file dirname [info script]]
}


#-----------------------------------------------------------------------
# Load app_athena(n) modules

source [file join $::app_athena::library main.tcl         ]
source [file join $::app_athena::library mod.tcl          ]
source [file join $::app_athena::library app.tcl          ]
source [file join $::app_athena::library log.tcl          ]
source [file join $::app_athena::library sanity.tcl       ]

#-----------------------------------------------------------------------
# Load app_athena(n) subpackages

source [file join $::app_athena::library shared modules.tcl]

# For Tk applications
if {$::tkLoaded} {
    source [file join $::app_athena::library ui      modules.tcl]
    source [file join $::app_athena::library wnbhood modules.tcl]
}







