#-----------------------------------------------------------------------
# TITLE:
#    pkgModules.tcl
#
# PROJECT:
#    athena - Athena Regional Stability Simulation
#
# DESCRIPTION:
#    app_athenawb(n) package modules file
#
#    Generated by Kite.
#-----------------------------------------------------------------------

#-----------------------------------------------------------------------
# Package Definition

# -kite-provide-start  DO NOT EDIT THIS BLOCK BY HAND
package provide app_athenawb 6.3.0a7
# -kite-provide-end

#-----------------------------------------------------------------------
# Required Packages

# Add 'package require' statements for this package's external 
# dependencies to the following block.  Kite will update the versions 
# numbers automatically as they change in project.kite.

# -kite-require-start ADD EXTERNAL DEPENDENCIES
package require projectlib
package require -exact athena 6.3.0a7
package require ctext 3.3
package require projectgui

namespace import ::projectlib::*
namespace import ::athena::*
namespace import ::projectgui::*

# -kite-require-end

#-----------------------------------------------------------------------
# Namespace definition

namespace eval ::app_athenawb:: {
    variable library [file dirname [info script]]
}


#-----------------------------------------------------------------------
# Load app_athenawb(n) modules

source [file join $::app_athenawb::library main.tcl         ]
source [file join $::app_athenawb::library mod.tcl          ]
source [file join $::app_athenawb::library app.tcl          ]
source [file join $::app_athenawb::library log.tcl          ]

#-----------------------------------------------------------------------
# Load app_athenawb(n) subpackages

source [file join $::app_athenawb::library shared  modules.tcl]
source [file join $::app_athenawb::library ui      modules.tcl]
source [file join $::app_athenawb::library wnbhood modules.tcl]







