#-----------------------------------------------------------------------
# TITLE:
#    pkgModules.tcl
#
# PROJECT:
#    athena - Athena Regional Stability Simulation
#
# DESCRIPTION:
#    app_athenawb(n) package modules file
#
#    Generated by Kite.
#-----------------------------------------------------------------------

#-----------------------------------------------------------------------
# Package Definition

# -kite-provide-start  DO NOT EDIT THIS BLOCK BY HAND
package provide app_athenawb 6.3.0a8
# -kite-provide-end

#-----------------------------------------------------------------------
# Required Packages

# Add 'package require' statements for this package's external 
# dependencies to the following block.  Kite will update the versions 
# numbers automatically as they change in project.kite.

# -kite-require-start ADD EXTERNAL DEPENDENCIES
package require projectlib
package require -exact athena 6.3.0a8
package require ctext 3.3
package require projectgui

namespace import ::projectlib::*
namespace import ::athena::*
namespace import ::projectgui::*

# -kite-require-end

#-----------------------------------------------------------------------
# Namespace definition

namespace eval ::app_athenawb:: {
    variable library [file dirname [info script]]
}


#-----------------------------------------------------------------------
# Load app_athenawb(n) modules

source [file join $::app_athenawb::library main.tcl               ]
source [file join $::app_athenawb::library mod.tcl                ]
source [file join $::app_athenawb::library app.tcl                ]
source [file join $::app_athenawb::library log.tcl                ]
source [file join $::app_athenawb::library apptypes.tcl           ]
source [file join $::app_athenawb::library gradient.tcl           ]
source [file join $::app_athenawb::library view.tcl               ]

source [file join $::app_athenawb::library activitybrowser.tcl    ]
source [file join $::app_athenawb::library actorbrowser.tcl       ]
source [file join $::app_athenawb::library appwin.tcl             ]
source [file join $::app_athenawb::library bsysbrowser.tcl        ]
source [file join $::app_athenawb::library civgroupbrowser.tcl    ]
source [file join $::app_athenawb::library capbrowser.tcl         ]
source [file join $::app_athenawb::library cgesheet.tcl           ]
source [file join $::app_athenawb::library coopbrowser.tcl        ]
source [file join $::app_athenawb::library ctexteditor.tcl        ]
source [file join $::app_athenawb::library cursebrowser.tcl       ]
source [file join $::app_athenawb::library demogbrowser.tcl       ]
source [file join $::app_athenawb::library demognbrowser.tcl      ]
source [file join $::app_athenawb::library detailbrowser.tcl      ]
source [file join $::app_athenawb::library econexpbrowser.tcl     ]
source [file join $::app_athenawb::library econngbrowser.tcl      ]
source [file join $::app_athenawb::library econtrol.tcl           ]
source [file join $::app_athenawb::library econpopbrowser.tcl     ]
source [file join $::app_athenawb::library absitbrowser.tcl       ]
source [file join $::app_athenawb::library frcgroupbrowser.tcl    ]
source [file join $::app_athenawb::library hookbrowser.tcl        ]
source [file join $::app_athenawb::library hrelbrowser.tcl        ]
source [file join $::app_athenawb::library iombrowser.tcl         ]
source [file join $::app_athenawb::library mapicon_situation.tcl  ]
source [file join $::app_athenawb::library mapicon_unit.tcl       ]
source [file join $::app_athenawb::library mapicons.tcl           ]
source [file join $::app_athenawb::library mapviewer.tcl          ]
source [file join $::app_athenawb::library nbchart.tcl            ]
source [file join $::app_athenawb::library nbcoopbrowser.tcl      ]
source [file join $::app_athenawb::library nbhoodbrowser.tcl      ]
source [file join $::app_athenawb::library nbrelbrowser.tcl       ]
source [file join $::app_athenawb::library ordersentbrowser.tcl   ]
source [file join $::app_athenawb::library orggroupbrowser.tcl    ]
source [file join $::app_athenawb::library plantbrowser.tcl       ] 
source [file join $::app_athenawb::library samsheet.tcl           ]
source [file join $::app_athenawb::library satbrowser.tcl         ]
source [file join $::app_athenawb::library scriptbrowser.tcl      ]
source [file join $::app_athenawb::library securitybrowser.tcl    ]
source [file join $::app_athenawb::library sigeventbrowser.tcl    ]
source [file join $::app_athenawb::library strategybrowser.tcl    ]
source [file join $::app_athenawb::library timechart.tcl          ]
source [file join $::app_athenawb::library vrelbrowser.tcl        ]
source [file join $::app_athenawb::library wmswin.tcl             ]

#-----------------------------------------------------------------------
# Load app_athenawb(n) subpackages

source [file join $::app_athenawb::library server  modules.tcl]
source [file join $::app_athenawb::library wnbhood modules.tcl]







