#-----------------------------------------------------------------------
# TITLE:
#    icons.tcl
#
# AUTHOR:
#    Will Duquette
#
# DESCRIPTION:
#    projectgui(n) package: standard icons
#
#    This module defines a set of standard icons for use in buttons,
#    etc.  All icons are defined in the ::projectgui::icon namespace; none
#    are exported.
#
#-----------------------------------------------------------------------

#-----------------------------------------------------------------------
# Icon definitions

namespace eval ::projectgui::icon:: {
    namespace import ::marsgui::mkicon

    mkicon ::projectgui::icon::locked22 {
        ......................
        ......XXXXXXXXXX......
        .....XXXXXXXXXXXX.....
        .....XX........XX.....
        .....XX........XX.....
        .....XX........XX.....
        .....XX........XX.....
        ...XXXXXXXXXXXXXXXX...
        ...X..............X...
        ...X...XXXXXXX....X...
        ...X...XXXXXXXX...X...
        ...X...XX....XX...X...
        ...X...XX....XX...X...
        ...X...XX....XX...X...
        ...X...XXXXXXXX...X...
        ...X...XXXXXXX....X...
        ...X...XX.........X...
        ...X...XX.........X...
        ...X...XX.........X...
        ...X..............X...
        ...XXXXXXXXXXXXXXXX...
        ......................
    } { . trans X black } d { X gray }

    mkicon ::projectgui::icon::unlocked22 {
        ......................
        ......XXXXXXXXXX......
        .....XXXXXXXXXXXX.....
        .....XX........XX.....
        .....XX........XX.....
        .....XX...............
        .....XX...............
        ...XXXXXXXXXXXXXXXX...
        ...X..............X...
        ...X...XXXXXXX....X...
        ...X...XXXXXXXX...X...
        ...X...XX....XX...X...
        ...X...XX....XX...X...
        ...X...XX....XX...X...
        ...X...XXXXXXXX...X...
        ...X...XXXXXXX....X...
        ...X...XX.........X...
        ...X...XX.........X...
        ...X...XX.........X...
        ...X..............X...
        ...XXXXXXXXXXXXXXXX...
        ......................
    } { . trans X black } d { X gray }



    mkicon ::projectgui::icon::nbpoly {
        ..XX..........
        ..X.XX........
        ..X...XX......
        ..X.....XX....
        .X........XX..
        .X..........XX
        .X...........X
        .X..X.....X..X
        X...XX....X..X
        X...X.X...X..X
        X...X..X..X..X
        X...X...X.X..X
        .X..X....XX..X
        .X..X.....X..X
        .X...........X
        .X.........XXX
        ..X.....XXX...
        ..X..XXX......
        ..XXX.........
    } { . trans  X black } d { X gray }



    mkicon ::projectgui::icon::actor12 {
        ...XX..
        ..XXXX.
        ..XXXX.
        ...XX..
        .XXXXXX
        .X.XX.X
        .X.XX.X
        ...XX..
        ..XXXX.
        ..X..X.
        ..X..X.
        ..X..X.
    } { . trans X black }

    mkicon ::projectgui::icon::hook12 {
        .........X
        .........X
        ......X..X
        ..xxx.XX.X
        .xxxxxX..X
        .xxxxx.XX.
        .xxxxx....
        ..xxx.....
        xxxxxxx...
        xxxxxxxx..
    } { . trans X black x #999999 }

    mkicon ::projectgui::icon::topic12 {
        ...........
        ...........
        ...........
        ....xxx....
        ...xxxxx...
        ...xxxxx...
        ...xxxxx...
        ....xxx....
        ..xxxxxxx..
        .xxxxxxxxx.
    } { . trans X black x blue }

    mkicon ::projectgui::icon::bsystem12 {
        ...........
        ...........
        ...........
        ....xxx....
        ...xxxxx...
        ...xxxxx...
        ...xxxxx...
        ....xxx....
        ..xxxxxxx..
        .xxxxxxxxx.
    } { . trans X black x red }

    mkicon ::projectgui::icon::message12 {
        ........
        ..XXXXXX
        .X.X...X
        XXXX...X
        X......X
        X.xxxx.X
        X......X
        X.xxx..X
        X......X
        X.xxxx.X
        X......X
        XXXXXXXX
    } { . trans X black x #666666 } 

    mkicon ::projectgui::icon::dollar12 {
       ....X....
       ..XXXXX..
       .XX.X.XX.
       .XX.X..X.
       ..X.X....
       ...XX....
       ....XX...
       ....X.X..
       .X..X.XX.
       .XX.X.XX.
       ..XXXXX..
       ....X....
    } { . trans X #216C2A }

    mkicon ::projectgui::icon::plant12 {
       ....xx..x
       ...xx..xx
       ..xx..xx.
       .xx..xx..
       .XX..XX..
       .XX..XX..
       .XX..XX..
       .XX..XX..
       .XXXXXX..
       .XXXXXX..
       .XXXXXXXX
       .XXXXXXXX
    } { . trans X black x #888888 }

    mkicon ::projectgui::icon::cannon12 {
       ............
       .........xx.
       x......xxxxx
       .x...xxxxxx.
       x..xxxxxxx..
       .xxxxxxxx...
       .xxxxxxX....
       xxxxxxXX....
       xxxxxXXX....
       .xxxXXXX....
       ...XXXXX....
       ...XXXXX....
    } { . trans X #94704D x black }

    mkicon ::projectgui::icon::heart12 {
       .........
       .........
       .........
       .XXX.XXX.
       XXXXXXXXX
       XXXXXXXXX
       .XXXXXXX.
       ..XXXXX..
       ...XXX...
       ....X....
       .........
       .........
    } { . trans X red } 


    mkicon ::projectgui::icon::blackheart12 {
       .........
       .........
       .........
       .XXX.XXX.
       XXXXXXXXX
       XXXXXXXXX
       .XXXXXXX.
       ..XXXXX..
       ...XXX...
       ....X....
       .........
       .........
    } { . trans X black } 

    mkicon ::projectgui::icon::blueheart12 {
       .........
       .........
       .........
       .XXX.XXX.
       XXXXXXXXX
       XXXXXXXXX
       .XXXXXXX.
       ..XXXXX..
       ...XXX...
       ....X....
       .........
       .........
    } { . trans X blue } 

    mkicon ::projectgui::icon::orangeheart12 {
       .........
       .........
       .........
       .XXX.XXX.
       XXXXXXXXX
       XXXXXXXXX
       .XXXXXXX.
       ..XXXXX..
       ...XXX...
       ....X....
       .........
       .........
    } { . trans X orange } 



    mkicon ::projectgui::icon::cap12 {
        .X.xx.X.
        X.xxxx.X
        X.xxxx.X
        .X.xx.X.
        ...xx...
        ...xx...
        ...xx...
        ...xx...
        ...xx...
        ...xx...
        ...xx...
        ...xx...
    } { . trans X black x "#666666"}

    mkicon ::projectgui::icon::nbhood12 {
        .......
        ...X...
        ..XXX..
        .XX,XX.
        XX,,,XX
        X,,,,,X
        .X,,,,X
        .X,,,,X
        X,,,,,X
        XX,,,,X
        ..XX,,X
        ....XX.
    } { . trans , "#00AA00" X black }

    mkicon ::projectgui::icon::group12 {
        ...X...
        ..XXX..
        ...X...
        .X...X.
        XXX.XXX
        .X...X.
        ...X...
        ..XXX..
        ...X...
        .X...X.
        XXX.XXX
        .X...X.
    } { . trans X black }

    mkicon ::projectgui::icon::civgroup12 {
        ...X...
        ..XXX..
        ...X...
        .X...X.
        XXX.XXX
        .X...X.
        ...X...
        ..XXX..
        ...X...
        .X...X.
        XXX.XXX
        .X...X.
    } { . trans X "#45DD11" }

    mkicon ::projectgui::icon::frcgroup12 {
        ...X...
        ..XXX..
        ...X...
        .X...X.
        XXX.XXX
        .X...X.
        ...X...
        ..XXX..
        ...X...
        .X...X.
        XXX.XXX
        .X...X.
    } { . trans X "#AA7744" }

    mkicon ::projectgui::icon::orggroup12 {
        ...X...
        ..XXX..
        ...X...
        .X...X.
        XXX.XXX
        .X...X.
        ...X...
        ..XXX..
        ...X...
        .X...X.
        XXX.XXX
        .X...X.
    } { . trans X "#B300B3" }

    mkicon ::projectgui::icon::group22 {
        ...............
        .......X.......
        ......XXX......
        .....XXXXX.....
        ......XXX......
        .......X.......
        ....X.....X....
        ...XXX...XXX...
        ..XXXXX.XXXXX..
        ...XXX...XXX...
        ....X.....X....
        .......X.......
        ......XXX......
        .....XXXXX.....
        ......XXX......
        .......X.......
        ....X.....X....
        ...XXX...XXX...
        ..XXXXX.XXXXX..
        ...XXX...XXX...
        ....X.....X....
        ...............
    } { . trans X black }

    mkicon ::projectgui::icon::civgroup22 {
        ...............
        .......X.......
        ......XXX......
        .....XXXXX.....
        ......XXX......
        .......X.......
        ....X.....X....
        ...XXX...XXX...
        ..XXXXX.XXXXX..
        ...XXX...XXX...
        ....X.....X....
        .......X.......
        ......XXX......
        .....XXXXX.....
        ......XXX......
        .......X.......
        ....X.....X....
        ...XXX...XXX...
        ..XXXXX.XXXXX..
        ...XXX...XXX...
        ....X.....X....
        ...............
    } { . trans X "#45DD11" }

    mkicon ::projectgui::icon::frcgroup22 {
        ...............
        .......X.......
        ......XXX......
        .....XXXXX.....
        ......XXX......
        .......X.......
        ....X.....X....
        ...XXX...XXX...
        ..XXXXX.XXXXX..
        ...XXX...XXX...
        ....X.....X....
        .......X.......
        ......XXX......
        .....XXXXX.....
        ......XXX......
        .......X.......
        ....X.....X....
        ...XXX...XXX...
        ..XXXXX.XXXXX..
        ...XXX...XXX...
        ....X.....X....
        ...............
    } { . trans X "#AA7744" }

    mkicon ::projectgui::icon::orggroup22 {
        ...............
        .......X.......
        ......XXX......
        .....XXXXX.....
        ......XXX......
        .......X.......
        ....X.....X....
        ...XXX...XXX...
        ..XXXXX.XXXXX..
        ...XXX...XXX...
        ....X.....X....
        .......X.......
        ......XXX......
        .....XXXXX.....
        ......XXX......
        .......X.......
        ....X.....X....
        ...XXX...XXX...
        ..XXXXX.XXXXX..
        ...XXX...XXX...
        ....X.....X....
        ...............
    } { . trans X "#B300B3" }

    mkicon ::projectgui::icon::eye12 {
        ............
        ............
        ..X..X..X...
        X..XXXXX..X.
        .XX.....XX..
        XX..XXX..XX.
        X..XXXXX..X.
        XX..XXX..XX.
        .XX.....XX..
        ...XXXXX....
        ............
        ............
    } { . trans X black , "#0AAEBD" }

    mkicon ::projectgui::icon::gpoly {
        ..XX..........
        ..X.XX........
        ..X...XX......
        ..X.....XX....
        .X........XX..
        .X..........XX
        .X..XXXXX....X
        .X.X.....X...X
        X..X.........X
        X..X.........X
        X..X..XXXX...X
        X..X.....X...X
        .X.X.....X...X
        .X..XXXXX....X
        .X...........X
        .X.........XXX
        ..X.....XXX...
        ..X..XXX......
        ..XXX.........
    } { . trans  X black } d { X gray }

    mkicon ::projectgui::icon::import22 {
        ......................
        ......................
        ......................
        ......................
        ......................
        ..........XXXXXXXXXX..
        ..........X........X..
        ..........X........X..
        ..........X..X.....X..
        ..........X..XX....X..
        .............XXX...X..
        ..XXXXXXXXXXXXXXX..X..
        .............XXX...X..
        ..........X..XX....X..
        ..........X..X.....X..
        ..........X........X..
        ..........X........X..
        ..........XXXXXXXXXX..
        ......................
        ......................
        ......................
        ......................
    } { . trans X black } d { X gray }

    mkicon ::projectgui::icon::export22 {
        ......................
        ......................
        ......................
        ......................
        ......................
        ..........XXXXXXXXXX..
        ..........X........X..
        ..........X........X..
        .....X....X........X..
        ....XX....X........X..
        ...XXX.............X..
        ..XXXXXXXXXXXXXXX..X..
        ...XXX.............X..
        ....XX....X........X..
        .....X....X........X..
        ..........X........X..
        ..........X........X..
        ..........XXXXXXXXXX..
        ......................
        ......................
        ......................
        ......................
    } { . trans X black } d { X gray }

    mkicon ::projectgui::icon::dash20 {
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
    } { . trans  X black } d { X gray }

    #-------------------------------------------------------------------
    # Block/Tactic/Condition status icons
    
    mkicon ::projectgui::icon::dash13 {
        ......................
        ......................
        ......................
        ......................
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ......................
        ......................
        ......................
        ......................
        ......................
    } { . trans  X gray }

    mkicon ::projectgui::icon::clock13r {
        ....XXXXX....
        ..XX.....XX..
        .X....X....X.
        .X....X....X.
        X.....X.....X
        X.....X.....X
        X.....XXX...X
        X...........X
        X...........X
        .X.........X.
        .X.........X.
        ..XX.....XX..
        ....XXXXX....
    } { . trans X red}

    mkicon ::projectgui::icon::smthumbdn13 {
        ........XXXXXXX......
        ..XXXXXXXXXXXXXX.....
        ..XXXXXXXXXXXXXXX....
        ..XXXXXXXXXXXXXXX....
        ..XXXXXXXXXXXXXXX....
        ..XXXXXXXXXXXXXX.....
        .......XXXXXXX.......
        ........XXXXXX.......
        ..........XXXX.......
        ...........XXXX......
        ...........XXXX......
        ............XXX......
        ............XX.......
    } { . trans  X "#FF0000" }

    mkicon ::projectgui::icon::smthumbup13 {
        ............XX.......
        ............XXX......
        ...........XXXX......
        ...........XXXX......
        ..........XXXX.......
        ........XXXXXX.......
        .......XXXXXXX.......
        ..XXXXXXXXXXXXXX.....
        ..XXXXXXXXXXXXXXX....
        ..XXXXXXXXXXXXXXX....
        ..XXXXXXXXXXXXXXX....
        ..XXXXXXXXXXXXXX.....
        ........XXXXXXX......
    } { . trans  X "#009900" }

    mkicon ::projectgui::icon::dollar13r {
       ....X....
       ..XXXXX..
       .XX.X.XX.
       .XX.X..X.
       ..X.X....
       ...XX....
       ....XX...
       ....X.X..
       .X..X.XX.
       .XX.X.XX.
       ..XXXXX..
       ....X....
       .........
    } { . trans X red }


    mkicon ::projectgui::icon::check13 {
        .................XX...
        ...X...........XXX....
        ...XX........XXXX.....
        ....XX.....XXXXX......
        ....XXX..XXXXXX.......
        ....XXXXXXXXXX........
        ....XXXXXXXXX.........
        .....XXXXXXX..........
        .....XXXXXX...........
        .....XXXXX............
        .....XXXX.............
        ......XX..............
        ......X...............
    } { . trans  X "#009900" } d { X gray }

    mkicon ::projectgui::icon::personnel13r {
        ...XX...
        ..XXXX..
        ..XXXX..
        ...XX...
        .XXXXXX.
        .X.XX.X.
        .X.XX.X.
        ...XX...
        ..XXXX..
        ..X..X..
        ..X..X..
        ..X..X..
        ........
    } { . trans X red }


    mkicon ::projectgui::icon::cap13p {
        ..X.xx.X..
        .X.xxxx.X.
        .X.xxxx.X.
        ..X.xx.X..
        ....xx....
        ....xx....
        ....xx....
        ....xx....
        ....xx....
        ....xx....
        ....xx....
        ....xx....
        ..........
    } { . trans X "#BA29C4" x "#BA29C4"}

    mkicon ::marsgui::icon::other13r {
        ...XXXXXX...
        ..XX....XX..
        ..XX.....XX.
        ........XX..
        .......XX...
        ......XX....
        .....XX.....
        .....XX.....
        ............
        .....XX.....
        ....XXXX....
        .....XX.....
        ............
    } { . trans X red }

    mkicon ::projectgui::icon::warning13r {
        ....XX....
        ...XXXX...
        ...XXXX...
        ...XXXX...
        ...XXXX...
        ....XX....
        ....XX....
        ....XX....
        ....XX....
        ..........
        ....XX....
        ...XXXX...
        ....XX....
    } { . trans X orange }

    mkicon ::projectgui::icon::error13r {
        ....XX....
        ...XXXX...
        ...XXXX...
        ...XXXX...
        ...XXXX...
        ....XX....
        ....XX....
        ....XX....
        ....XX....
        ..........
        ....XX....
        ...XXXX...
        ....XX....
    } { . trans X orange }

    #-------------------------------------------------------------------
    # Econ disable/enable switch icons
    mkicon ::projectgui::icon::switchon {
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X............................................................X
        X................................XXXXXXXXXXXXXXXXXXXXXXXXXXX.X
        X................................XxxxxxxxxxxxxxxxxxxxxxxxxxX.X
        X................................Xxx-xxx-xxx-xxx-xxx-xxx-xxX.X
        X.....XXXXXX.....................Xxx-xxx-xxx-xxx-xxx-xxx-xxX.X
        X....XXXXXXXX....................Xxx-xxx-xxx-xxx-xxx-xxx-xxX.X
        X...XX......XX...................Xxx-xxx-xxx-xxx-xxx-xxx-xxX.X
        X...XX......XX...................Xxx-xxx-xxx-xxx-xxx-xxx-xxX.X
        X...XX......XX...XX..XXX.........Xxx-xxx-xxx-xxx-xxx-xxx-xxX.X
        X...XX......XX...XX.XXXXX........Xxx-xxx-xxx-xxx-xxx-xxx-xxX.X
        X...XX......XX...XXXX..XXX.......Xxx-xxx-xxx-xxx-xxx-xxx-xxX.X
        X...XX......XX...XXX....XX.......Xxx-xxx-xxx-xxx-xxx-xxx-xxX.X
        X...XX......XX...XX.....XX.......Xxx-xxx-xxx-xxx-xxx-xxx-xxX.X
        X...XX......XX...XX.....XX.......Xxx-xxx-xxx-xxx-xxx-xxx-xxX.X
        X...XX......XX...XX.....XX.......Xxx-xxx-xxx-xxx-xxx-xxx-xxX.X
        X...XX......XX...XX.....XX.......Xxx-xxx-xxx-xxx-xxx-xxx-xxX.X
        X...XX......XX...XX.....XX.......Xxx-xxx-xxx-xxx-xxx-xxx-xxX.X
        X....XXXXXXXX....XX.....XX.......Xxx-xxx-xxx-xxx-xxx-xxx-xxX.X
        X.....XXXXXX.....XX.....XX.......Xxx-xxx-xxx-xxx-xxx-xxx-xxX.X
        X................................XxxxxxxxxxxxxxxxxxxxxxxxxxX.X
        X................................XXXXXXXXXXXXXXXXXXXXXXXXXXX.X
        X............................................................X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    } { 
        . "#CCFF99" X black - "#525252" x lightgrey
    } d {
        . lightgrey X black - lightgrey x lightgrey 
    }
        
    mkicon ::projectgui::icon::switchoff {
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X............................................................X
        X.XXXXXXXXXXXXXXXXXXXXXXXXXXX................................X
        X.XxxxxxxxxxxxxxxxxxxxxxxxxxX................................X
        X.Xxx-xxx-xxx-xxx-xxx-xxx-xxX................................X
        X.Xxx-xxx-xxx-xxx-xxx-xxx-xxX....XXXXXX......................X
        X.Xxx-xxx-xxx-xxx-xxx-xxx-xxX...XXXXXXXX.....XXX......XXX....X
        X.Xxx-xxx-xxx-xxx-xxx-xxx-xxX..XX......XX...XXXXX....XXXXX...X
        X.Xxx-xxx-xxx-xxx-xxx-xxx-xxX..XX......XX..XXX..XX..XXX..XX..X
        X.Xxx-xxx-xxx-xxx-xxx-xxx-xxX..XX......XX..XX...XX..XX...XX..X
        X.Xxx-xxx-xxx-xxx-xxx-xxx-xxX..XX......XX..XX...XX..XX...XX..X
        X.Xxx-xxx-xxx-xxx-xxx-xxx-xxX..XX......XX..XX.......XX.......X
        X.Xxx-xxx-xxx-xxx-xxx-xxx-xxX..XX......XX..XX.......XX.......X
        X.Xxx-xxx-xxx-xxx-xxx-xxx-xxX..XX......XX..XXXXX....XXXXX....X
        X.Xxx-xxx-xxx-xxx-xxx-xxx-xxX..XX......XX..XXXXX....XXXXX....X
        X.Xxx-xxx-xxx-xxx-xxx-xxx-xxX..XX......XX..XX.......XX.......X
        X.Xxx-xxx-xxx-xxx-xxx-xxx-xxX..XX......XX..XX.......XX.......X
        X.Xxx-xxx-xxx-xxx-xxx-xxx-xxX..XX......XX..XX.......XX.......X
        X.Xxx-xxx-xxx-xxx-xxx-xxx-xxX...XXXXXXXX...XX.......XX.......X
        X.Xxx-xxx-xxx-xxx-xxx-xxx-xxX....XXXXXX....XX.......XX.......X
        X.XxxxxxxxxxxxxxxxxxxxxxxxxxX................................X
        X.XXXXXXXXXXXXXXXXXXXXXXXXXXX................................X
        X............................................................X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    } {
        . "#FFA9A7" X black - "#525252" x lightgrey
    } d {
        . lightgrey X black - lightgrey x lightgrey 
    }
    
    mkicon ::projectgui::icon::reset22 {
        ......................
        ......X...............
        .....XX...............
        ....XXX...............
        ...XXXX...............
        ..XXXXXXXXXXXXXXXX....
        .XXXXXXXXXXXXXXXXXX...
        ..XXXXXXXXXXXXXXXXXX..
        ...XXXX.........XXXX..
        ....XXX..........XXX..
        .....XX..........XXX..
        ......X..........XXX..
        .................XXX..
        .................XXX..
        .................XXX..
        .................XXX..
        .................XXX..
        ................XXXX..
        ..XXXXXXXXXXXXXXXXXX..
        ..XXXXXXXXXXXXXXXXX...
        ..XXXXXXXXXXXXXXXX....
        ......................
        ......................
    } { . trans X black } d { X gray }
}


