#-------------------------------------------------------------------------
# TITLE:
#    pkgIndex.tcl
#
# PROJECT:
#    athena-sim - Athena Regional Stability Simulation
#
# DESCRIPTION:
#    projectgui(n) package index file
#
#    Generated by Kite.
#-------------------------------------------------------------------------

# -kite-ifneeded-start  DO NOT EDIT THIS BLOCK BY HAND
package ifneeded projectgui 6.3.0 [list source [file join $dir pkgModules.tcl]]
# -kite-ifneeded-end
