# Tcl package index file, version 1.1

# This file is generated by the MakeIndex script in the tclhttpd 
# lib directory.  The goal is to not pollute the package namespace
# until you package require httpd

package ifneeded httpd 1.7 "
	source \[file join [list $dir] httpd.tcl\]
	package ifneeded httpd::utils 1.0 \[list source \[file join [list $dir] utils.tcl\]\]
"
